# Every value from the environment.
contoso_gold:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      host: "{{ env_var('SNOWFLAKE_HOST') }}"
      port: "{{ env_var('SNOWFLAKE_PORT') | as_number }}"
      protocol: http
      insecure_mode: true
      threads: 1
